version: '3'
services:
  postgres:
    image: "postgres:9.5.16-alpine"
    ports:
      - "5434:5432"
    container_name: "library_db"
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres/data:/var/lib/postgresql/data